apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c29tZXBhc3N3b3Jk
  MYSQL_USER: bXlzcWw=
  MYSQL_PASSWORD: bXlzcWw=
  NAME: dG9kb19kYg==
  USER: bXlzcWw=
  PASSWORD: c29tZXBhc3N3b3Jk
  HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==
---